version: '3.8'

services:
  # PostgreSQL Database Service
  db:
    image: postgres:15
    container_name: odoo18-db
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=MyStrongAdminPassword!
      - POSTGRES_DB=postgres
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: always

  # Odoo 18 Application Service
  odoo:
    image: odoo:18.0
    container_name: odoo18-app
    depends_on:
      - db
    ports:
      - "8069:8069" # Odoo web interface
      - "8072:8072" # Live chat (optional)
    volumes:
      # Mounts a local folder for your custom addons
      - ./addons:/mnt/extra-addons
      # Mounts a volume to persist Odoo's data (filestore)
      - odoo-web-data:/var/lib/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - PORT=5432
    restart: always

volumes:
  odoo-db-data:
  odoo-web-data:
